image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме - не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-ibank.jar -P:profile=test &
  - chmod +x gradlew
  - java -jar ./artifacts/log4j-1.2-api-2.21.1.jar &

build_script:
    - ./gradlew test --info